# Generated by Django 4.2.9 on 2024-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='plant_images/default_plant.jpg', upload_to='plant_images'),
        ),
        migrations.AddField(
            model_name='plant',
            name='light_requirements',
            field=models.CharField(default='Unknown Light Requirements', max_length=100),
        ),
    ]
